FROM python

WORKDIR "/home/egor/Documents/BSUIR/4sem_IGI_Python/Labs_Python_IGI/Lab_1/Task1/1.2"

COPY ["calculate.py", "./"]
COPY ["constant.py", "./"]
COPY ["util.py", "./"]

CMD ["python", "calculate.py"]