FROM python

WORKDIR "/home/egor/Documents/BSUIR/4sem_IGI_Python/Labs_Python_IGI/Lab_2/Task1"

COPY ["main.py", "./"]
COPY ["util.py", "./"]
COPY ["constant.py", "./"]
COPY ["data.txt", "./"]

ENTRYPOINT ["python", "main.py"]