FROM python

WORKDIR "/home/egor/Documents/BSUIR/4sem_IGI_Python/Labs_Python_IGI/Lab_2/Task2"

COPY ["container_CLI.py", "./"]
COPY ["container.py", "./"]
COPY ["main.py", "./"]
COPY ["data.txt", "./"]

ENTRYPOINT ["python", "main.py"]