# Generated by Django 4.2.1 on 2023-09-10 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_advertising_article_coupon_partner_question_reviews_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='Vacancies',
            new_name='Vacancy',
        ),
        migrations.AlterField(
            model_name='workerinfo',
            name='worker',
            field=models.OneToOneField(limit_choices_to={'is_stuff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
