# Generated by Django 4.2.1 on 2023-09-10 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_rename_reviews_review_rename_vacancies_vacancy_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertising',
            new_name='Advertisement',
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterModelOptions(
            name='workerinfo',
            options={'verbose_name_plural': 'Workers info'},
        ),
        migrations.AlterField(
            model_name='workerinfo',
            name='worker',
            field=models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
