# Generated by Django 4.2.1 on 2023-09-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_advertising_advertisement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='advertisement'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to='partner'),
        ),
        migrations.AlterField(
            model_name='workerinfo',
            name='image',
            field=models.ImageField(upload_to='worker_info'),
        ),
    ]
