# Generated by Django 4.2.1 on 2023-09-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_advertisement_image_alter_article_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='patner_name',
            new_name='partner_name',
        ),
    ]
