# Generated by Django 4.2.1 on 2023-09-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_history_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
