# Generated by Django 4.2.1 on 2023-09-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_client'),
        ('store', '0014_coupon_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
