# Generated by Django 4.2.1 on 2023-10-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_delete_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='sate_of_creation',
            new_name='date_of_creation',
        ),
    ]
