# Generated by Django 4.2.1 on 2023-11-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_sate_of_creation_review_date_of_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
            ],
        ),
    ]
